trigger:
- master

pr:
- master

variables:
  solution: '**/CodeConverter.sln'
  buildPlatform: 'Any CPU'
  buildVersion: '8.1.1.$(Build.BuildId)'

pool:
  vmImage: 'windows-2019'
strategy:
  matrix:
    Config_Release:
        buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .net core 3.1'
  inputs:
    packageType: sdk
    version: '3.1.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Assembly-Info-NetCore@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/CodeConverter.csproj'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(buildVersion)'
    FileVersionNumber: '$(buildVersion)'
    PackageVersion: '$(buildVersion)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: ''
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True
    runSettingsFile: Tests/continuousintegration.runsettings

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/CodeConverter.csproj'
    versioningScheme: 'off'

- task: CopyFiles@2
  displayName: Move vsix/nupkg to publish directory
  inputs:
    contents: |
      **\ICSharpCode.CodeConverter.*.nupkg
      **\ICSharpCode.CodeConverter.VsExtension.vsix
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  displayName: Publish Artifacts
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactName: VSExtensionAndNupkg